# Generated by Django 5.1 on 2024-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='lock',
            field=models.BooleanField(default=True),
        ),
    ]
